server:
  port: 11100
  context-path: /eureka

spring:
  application:
    name: springboot-eureka-server

eureka:
  instance:
    hostname: forsrc.local
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${server.context-path}/eureka/ 